### ISSUE TITLE
Ability to automatically create a project

### ISSUE THREAD

**Issue by elizabethhalper** [projector-cli/projector#14]
Currently `pjr project init` initializes the ability to use projector, however we'd like the ability to create a remote project. This story is to create a new command that allows the user to set up a project in Azure devops

AC's:
- update command to use inputs/respond properly to incorrect inputs
- implement necessary methods in agile service provider leveraging azdo library
- ensure an AzDo project is created

This will probably be broken up into multiple issues as we begin implementation.

**Comment by tbarlow12** [comment]
Just to clarify (for posterity), `pjr project init` doesn't actually do anything w/ DevOps. It's more for your local project configuration. It will generate a default `projector.json` in you working directory for you to then add configuration values. If we need to rename or add additional docs, let's do that

**Comment by tbarlow12** [comment]
Or, if we need to add another feature for initializing a project, that's good too

**Comment by elizabethhalper** [comment]
Edited description to be about general project creation--starting with AzDo as our default. A new story will be created for github projects.
